name: Android Cloud Factory

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¦ Download your code
      uses: actions/checkout@v4

    - name: â˜• Setup Java Engine
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: ğŸ˜ Setup Gradle Builder
      uses: gradle/actions/setup-gradle@v3

    - name: ğŸ”¨ Compile Android APK
      run: gradle assembleDebug

    - name: ğŸš€ Upload APK for Download
      uses: actions/upload-artifact@v4
      with:
        name: Syrja-Node-App
        path: app/build/outputs/apk/debug/*.apk
